### ISSUE TITLE
Can change to latest version azerothcore?

### ISSUE THREAD

**Issue by jimteck** [trickerer/Traumas#1]
Hi, can change this script to latest version azeroth core , or rechange to azeroth core module?

**Comment by trickerer** [comment]
AC module is impossible currently, its `OnDamage()` hook doesn't provide required info.

Otherwise it shouldn't be too difficult to port traumas code to AC. Original idea didn't get much attention - sorry if I'm not in a hurry to do anything with this project.

**Comment by jimteck** [comment]
Ok. Is it possible to implement the reforging of rochet2?
https://rochet2.github.io/Reforging.html

**Comment by trickerer** [comment]
> Ok. Is it possible to implement the reforging of rochet2? https://rochet2.github.io/Reforging.html

What is this, just a random question?
Surely it's possible, I'm not going to do it though. What I'm not sure about is if it wasn't already ported to AC.

**Comment by trickerer** [comment]
https://github.com/trickerer/Traumas/commit/cab0033dd00bba5461880030f5e99f778bad67d5
